name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r docs -x localhost
#    - name: Fail if there were link errors
#      run: exit ${{ steps.lc.outputs.exit_code }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          GIT_USER: ${{ secrets.GH_NAME }}
          USE_SSH: true
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_NAME }}
          touch .env
          echo "ALGOLIA_API_KEY=${{ secrets.ALGOLIA_KEY }}" > .env
          echo "ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }}" >> .env
          echo "ALGOLIA_INDEX_NAME=datahighway" >> .env
          source .env
          npm install
          npm run deploy